### ISSUE TITLE
Please update NVdSync and cpe2cve tools to work for NVD JSON 1.1 

### ISSUE THREAD

**Issue by navneetmaurya** [facebookincubator/nvdtools#116]
Please update nvdsync and cpe2cve tools to work with NVD JSON 1.1 Schema

**Comment by skogtwin** [comment]
#117 addresses this for nvdsync, we still need to address cpe2cve and related tools.

**Comment by skogtwin** [comment]
Actually, my bad, 1.1 seems to be compatible with 1.0 for all intents and purposes of cpe2cve. This seems to be resolved.
