### ISSUE TITLE
SyncError as return value

### ISSUE THREAD

**Issue by cr-idoschwartzman** [facebookincubator/nvdtools#123]
In the Do function in sync.go, SyncError is returned as an error value, and that value is later tested for nil. This is a bug, as a nil value returned as error (which is an interface) will produce an interface object with nil as the value, and SyncError as the type, causing the caller to mistakenly classify it as an error.

**Comment by skogtwin** [comment]
SyncError is defined to be a slice of string; `var x []string` declares a nil-slice: https://play.golang.org/p/LGhry8XKJsm

**Comment by skogtwin** [comment]
My bad, got your point. Thanks for reporting!
