### ISSUE TITLE
Creation of a web API to use nvdtools as a vulnerability monitoring service.

### ISSUE THREAD

**Issue by s-guedon** [facebookincubator/nvdtools#153]
Hello,

I work for the group LINAGORA, and we have the project `LinInfoSec` to build a notification tool to monitor CVE publications relating to a given list of software, and integrate it with our ticketing system [SmartSLA](https://smartsla.org/).
To bootstrap our project, we would like to base it on an existing OSS project and nvdtools is a great candidate.

If we do so, we would add some functionality to the project:

- A web API including:
    - Efficient search for the CPE dictionary
    - Configuring a set of CPE URIs to be monitored for new CVEs
- Automatic fetching of recent CVE publications 
- A notification system when a new CVE matches the mentioned set of CPEs

We would implement these as a separate binary, then use this API to provide additionnal functionnality in our product [SmartSLA](https://smartsla.org/).

We could fork the project to implement these features on our own, regardless of your long term objectives for nvdtools, but we much rather collaborate with you so that our contributions can be merged into nvdtools.
Would you be interested to collaborate with us on such a project? If you are, we could meet through video conference to discuss it.

Thanks,  
Sosthène Guédon for LINAGORA

**Comment by skogtwin** [comment]
Hi Sosthène.

We absolutely encourage the contribution to this project. There are, of course, some legal nuances, mostly related to the licensing of LinInfoSec, accepting contributor's agreement etc. Having a VC sounds like a great idea. Unfortunately your account does not expose any details I could use to reach out. Please, pen me an email so we could continue this conversation.

Cheers!
D.

**Comment by ssosthene-guedon** [comment]
I have contacted you by email with you an email at dvl@fb.com from your profile. If for some reason you didn't receive it my address is [sguedon@linagora.com](mailto:sguedon@linagora.com)

**Comment by ssosthene-guedon** [comment]
As said in the VC, I will describe here in more details our goals.
We have a ticketing system [SmartSLA](https://smartsla.org/) that we use as a help-desk for our customers. We currently monitor various CVE feeds for vulnerabilities affecting our clients. The process is only partially automated and requires a lot of manual work to filter false positives and we would like to improve it, basing our new work on nvdtools.

To make this work, we intend to make it work as a service (that we would like to be merged into nvdtools) that would expose a REST API that SmartSLA could interact with.

The service would use a database that would store the CPE dictionnary, and the software configurations that we need to monitor.
It would then regularly fetch the recent CVE feeds from NVD and other sources and match the recent publications against the monitored software configurations.
It could then be configured to reach an specified endpoint to notify it of the vulnerabilty (in our case it would be a specific SmartSLA endpoint to create tickets).

As such the API we would implement would have the following functionalities :
- Set the list of configurations to monitor (in our case the configurations would come from SmartSLA)
- Fetch regularly CVEs feeds (approximately every two ours for NVD for example)
- Search the CPE dictionary (this would be useful to configure the monitored configurations from SmartSLA) 

Theses functionalities would be made configurable to keep the tool generic and not bound to SmartSLA.

**Comment by skogtwin** [comment]
This has not been updated in more than a year. Closing for now, feel free to re-open if any actions are still required.
