### ISSUE TITLE
Retirement of NVD Datafeeds.

### ISSUE THREAD

**Issue by theslothuk** [facebookincubator/nvdtools#207]
The NVD reports that it is retiring its feeds in favor of an API e.g. :

https://nvd.nist.gov/vuln/data-feeds

Does that mean the related nvd libraries will cease to function on post Sept 2023 NVD data?

**Comment by ImanolBarba** [comment]
At this moment, nvdtools is in maintenance mode, we don't plan on adding new features, including the new API, so unfortunately yes, it will cease to function.

We are however happy to accept contributions or co-maintainers.

**Comment by theslothuk** [comment]
It is simple enough to use the api 2.0 to download all CVE's (Basically all data available) in json. I am struggling to convert that to CSV. Is there a way to adapt the code here so it just points at that json file and converts it to .csv?I do not understand the code here. I can share my python that gets the full json data if someone can morph the two things together? Then, it's easy to put the csv data into a database

**Comment by ImanolBarba** [comment]
Unfortunately there isn't such a thing right now, and we aren't working on this issue as mentioned before, but we welcome contributions.

Closing the issue as the original question has been answered
