### ISSUE TITLE
Add support to include CWE and CVSS score in the output of cpe2cve

### ISSUE THREAD

**Issue by fiorix** [facebookincubator/nvdtools#24]
Today, the output of cpe2cve only includes a CVE, and optionally the matched CPEs. We should have flags to optionally include the CWE and CVSS score (the base score) in the processor's output.

My suggestion is to allow -cwe=N and -cvss=N where N is the column number of the output.

**Comment by skogtwin** [comment]
Yeah, I think this not gonna fly. You see, cpe2cve was designed to be used with multitude of feeds from different providers. As long as we have just id and platform configuration for each vulnerability, merging duplicates is more or less clear task. But if we support more metadata, it becomes much more complicated.
I think it is better to write a separate program, that would consume the output of cpe2cve, load the feed  and decorate the input CSV with whatever fields from that feed we need.

**Comment by fiorix** [comment]
Can we reconsider? For long term, remove the merging functionality from cpe2cve and do it in a separate tool and make CWE and CVSS available in the cpe2cve output instead?

The issue with merging: if you pass multiple feeds to cpe2cve and it does merging internally you no longer have access to the actual database that was used for merging, and there's no guarantees that the logic of merging won't change across different versions of the tool. Having the merge handled by a separate tool would allow to have the output dumped to a file that produces consistent results given the same database and CPE inventory.

The use case for producing CWE and CVSS is to get the processed inventory with information that is *already* in the database during processing, as opposed to having to re-index the database and decorate the processed output in a separate stage.

**Comment by skogtwin** [comment]
Should be solved by #30
